apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-security
  namespace: financial-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authorization-security
  template:
    metadata:
      labels:
        app: authorization-security
    spec:
      containers:
      - name: authorization
        image: your-registry/authorization:latest
        ports:
        - containerPort: 8083
      - name: security-control
        image: your-registry/security-control:latest
        ports:
        - containerPort: 8084
