apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-portfolio
  namespace: financial-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reporting-portfolio
  template:
    metadata:
      labels:
        app: reporting-portfolio
    spec:
      containers:
      - name: reporting-analytics
        image: your-registry/reporting-analytics:latest
        ports:
        - containerPort: 8085
      - name: portfolio
        image: your-registry/portfolio:latest
        ports:
        - containerPort: 8086
