apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-client-account
  namespace: financial-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-client-account
  template:
    metadata:
      labels:
        app: transaction-client-account
    spec:
      containers:
      - name: transaction
        image: your-registry/transaction:latest
        ports:
        - containerPort: 8088
      - name: client-account
        image: your-registry/client-account:latest
        ports:
        - containerPort: 8089
