# microservices.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices
  template:
    metadata:
      labels:
        app: microservices
    spec:
      containers:
        - name: nlp-service
          image: nlp-service-image:latest
          ports:
            - containerPort: 5001
        - name: integration-service
          image: integration-service-image:latest
          ports:
            - containerPort: 5002
        - name: adaptability-service
          image: adaptability-service-image:latest
          ports:
            - containerPort: 5003
        - name: performance-service
          image: performance-service-image:latest
          ports:
            - containerPort: 5004
        - name: security-service
          image: security-service-image:latest
          ports:
            - containerPort: 5005
        - name: scalability-service
          image: scalability-service-image:latest
          ports:
            - containerPort: 5006
        - name: usability-service
          image: usability-service-image:latest
          ports:
            - containerPort: 5007
        - name: maintainability-service
          image: maintainability-service-image:latest
          ports:
            - containerPort: 5008
        - name: compatibility-service
          image: compatibility-service-image:latest
          ports:
            - containerPort: 5009
---
apiVersion: v1
kind: Service
metadata:
  name: microservices
spec:
  selector:
    app: microservices
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
