apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-compliance
  namespace: financial-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-compliance
  template:
    metadata:
      labels:
        app: transaction-compliance
    spec:
      containers:
      - name: transaction
        image: your-registry/transaction:latest
        ports:
        - containerPort: 8087
      - name: compliance
        image: your-registry/compliance:latest
        ports:
        - containerPort: 8088
