version: '3.9'

services:
  environmental-sensors:
    image: sensors-image
    container_name: environmental_sensors
    ports:
      - "8001:8001"
    networks:
      - monitoring-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
    # Collects environmental data and runs with lightweight resource allocation.

  integration-with-building-systems:
    image: integration-image
    container_name: integration_building_systems
    ports:
      - "8002:8002"
    networks:
      - monitoring-network
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "512M"
    # Integrates environmental sensors with building systems.

  alerting-and-notification:
    image: alerting-image
    container_name: alerting_notification
    ports:
      - "8003:8003"
    networks:
      - monitoring-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
    # Handles notifications and alerts for critical system events.

  remote-access-control:
    image: remote-access-image
    container_name: remote_access_control
    ports:
      - "8004:8004"
    networks:
      - monitoring-network
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "512M"
    # Provides remote access for administrative control.

  scalability-management:
    image: scalability-image
    container_name: scalability_management
    ports:
      - "8005:8005"
    networks:
      - monitoring-network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
    # Manages scalability and multi-building support.

  real-time-monitoring:
    image: monitoring-image
    container_name: real_time_monitoring
    ports:
      - "8006:8006"
    networks:
      - monitoring-network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
    # Provides real-time status updates and analytics.

  data-logging-storage:
    image: data-storage-image
    container_name: data_logging_storage
    ports:
      - "5432:5432"
    networks:
      - monitoring-network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monitoring_system
    volumes:
      - data_storage:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "4G"
    # Stores historical data with persistent volume for durability.

  event-producer:
    image: event-producer-image
    container_name: event_producer
    ports:
      - "8007:8007"
    networks:
      - monitoring-network
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "512M"
    # Produces system events for processing.

  event-bus:
    image: event-bus-image
    container_name: event_bus
    ports:
      - "8008:8008"
    networks:
      - monitoring-network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
    # Facilitates communication between event producers and consumers.

  event-consumer:
    image: event-consumer-image
    container_name: event_consumer
    ports:
      - "8009:8009"
    networks:
      - monitoring-network
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "512M"
    # Consumes events from the bus for further processing.

networks:
  monitoring-network:
    driver: bridge
    # Shared bridge network for service-to-service communication.

volumes:
  data_storage:
    # Persistent volume for database storage.
