apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-product
  namespace: financial-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: investment-product
  template:
    metadata:
      labels:
        app: investment-product
    spec:
      containers:
      - name: investment-product
        image: your-registry/investment-product:latest
        ports:
        - containerPort: 8093
