apiVersion: apps/v1
kind: Deployment
metadata:
  name: performance-client-account
  namespace: financial-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: performance-client-account
  template:
    metadata:
      labels:
        app: performance-client-account
    spec:
      containers:
      - name: performance-metrics
        image: your-registry/performance-metrics:latest
        ports:
        - containerPort: 8091
      - name: client-account
        image: your-registry/client-account:latest
        ports:
        - containerPort: 8092
